-- =============================================
-- Migration: 003_issue_tracking
-- Description: Issue tracking feature with pre-baked AI reports and fake door testing
-- Created: 2026-01
-- =============================================

-- ===========================================
-- Part 1: Update newsletters table
-- ===========================================

-- Add all_keywords column for issue tracking search
ALTER TABLE public.newsletters
ADD COLUMN IF NOT EXISTS all_keywords TEXT[] DEFAULT '{}';

-- Create GIN index for keyword search
CREATE INDEX IF NOT EXISTS idx_newsletters_keywords
  ON public.newsletters USING GIN (all_keywords);

-- Add column comment
COMMENT ON COLUMN public.newsletters.all_keywords IS 'AI-extracted keywords for issue tracking search';

-- ===========================================
-- Part 2: Create issue_tracks table
-- ===========================================

CREATE TABLE IF NOT EXISTS public.issue_tracks (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  keyword TEXT NOT NULL,
  display_title TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  last_report_html TEXT,
  last_report_data JSONB,
  last_updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  CONSTRAINT issue_tracks_pkey PRIMARY KEY (id),
  CONSTRAINT issue_tracks_keyword_key UNIQUE (keyword)
);

-- Enable Row Level Security
ALTER TABLE public.issue_tracks ENABLE ROW LEVEL SECURITY;

-- Create partial index for active issues
CREATE INDEX IF NOT EXISTS idx_issue_tracks_active
  ON public.issue_tracks (is_active) WHERE is_active = true;

-- RLS Policies
-- Frontend (Anon Key): SELECT only for active issues
CREATE POLICY "Allow public read active issues"
  ON public.issue_tracks
  FOR SELECT
  TO anon
  USING (is_active = true);

-- Backend (Service Role): Full access (bypasses RLS)

-- Add table comment
COMMENT ON TABLE public.issue_tracks IS 'Tracked issues with pre-baked AI reports for deep dive feature';
COMMENT ON COLUMN public.issue_tracks.keyword IS 'Primary search keyword (e.g., "의대 증원")';
COMMENT ON COLUMN public.issue_tracks.display_title IS 'User-facing title for the issue';
COMMENT ON COLUMN public.issue_tracks.last_report_html IS 'Pre-baked HTML report generated by AI';
COMMENT ON COLUMN public.issue_tracks.last_report_data IS 'Structured JSON data for API access';

-- ===========================================
-- Part 3: Create payment_intent_logs table
-- ===========================================

CREATE TABLE IF NOT EXISTS public.payment_intent_logs (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  issue_track_id UUID REFERENCES public.issue_tracks(id),
  target_issue TEXT NOT NULL,
  ip_address INET,
  user_agent TEXT,
  referrer TEXT,
  clicked_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  CONSTRAINT payment_intent_logs_pkey PRIMARY KEY (id)
);

-- Enable Row Level Security (backend only, no public access)
ALTER TABLE public.payment_intent_logs ENABLE ROW LEVEL SECURITY;

-- Create indexes for analytics queries
CREATE INDEX IF NOT EXISTS idx_payment_intent_logs_issue
  ON public.payment_intent_logs (target_issue, clicked_at DESC);

CREATE INDEX IF NOT EXISTS idx_payment_intent_logs_date
  ON public.payment_intent_logs (clicked_at DESC);

-- Add table comment
COMMENT ON TABLE public.payment_intent_logs IS 'Fake door payment intent logging for user research';
COMMENT ON COLUMN public.payment_intent_logs.issue_track_id IS 'FK to issue_tracks (nullable for unlinked searches)';
COMMENT ON COLUMN public.payment_intent_logs.target_issue IS 'Keyword of the issue where user clicked payment button';
COMMENT ON COLUMN public.payment_intent_logs.ip_address IS 'User IP address for duplicate detection';
